devices:
  - name: Pixel
    os: Android
    udid: 98261FFBA001GR
    hub_serial: 11212
    hub_port: 1
  - name: iPhone XS Max
    os: iOS
    udid: 1faff2315aa7d5cefcf0d5e0df3f589e714141e6
    hub_serial: 11212
    hub_port: 2